### ISSUE TITLE
Regarding the issue of rviz

### ISSUE THREAD

**Issue by zhengnx0906** [abeleinin/gp-navigation#1]
Why can't the cost map display it when I'm planning? Is it because the CPU processing time is too long?

**Comment by zhengnx0906** [comment]
![屏幕截图 2024-06-13 16:46:29](https://github.com/abeleinin/gp-navigation/assets/55745484/a9ff3337-6fd0-42e3-b567-8cdc0c327f8e)

**Comment by 111llll11** [comment]
Brother, did you solve the problem

**Comment by abeleinin** [comment]
Is the code not behaving like this portion of the presentation video?
https://youtu.be/rYURYf1w7f8?si=1huH_7plZaEbCmge&t=109
From what I remember, the cost map and planning should happen and be presented in lockstep. 

Otherwise, this could be an issue of clearing the cost map Rviz objects too early, which shouldn't be difficult to adjust if you're looking for a different visualization. Let me know what behavior you're expecting, and I'll try to help.

**Comment by zhengnx0906** [comment]
This problem was automatically solved. I don't know why.
